const products = [
  {
    title: "B12 medicine",
    price: "$19.00 USD",
    originalPrice: "$25.00 USD",
    image: "/uploads/product1.svg",
    category: "Medicines",
  },
  {
    title: "Tonometer",
    price: "$19.00 USD",
    originalPrice: "$30.00 USD",
    image: "/uploads/product2.svg",
    category: "Devices",
  },
  {
    title: "ECG cardiograph",
    price: "$20.00 USD",
    originalPrice: "$30.00 USD",
    image: "/uploads/product3.svg",
    category: "Devices",
  },
  {
    title: "Blood glucose meter",
    price: "$15.00 USD",
    originalPrice: "$25.00 USD",
    image: "/uploads/product4.svg",
    category: "Devices",
  },
  {
    title: "Lab hand gloves",
    price: "$20.00 USD",
    originalPrice: "$25.00 USD",
    image: "/uploads/product5.svg",
    category: "Accessories",
  },
  {
    title: "Stethoscope",
    price: "$20.00 USD",
    originalPrice: "$28.00 USD",
    image: "/uploads/product6.svg",
    category: "Devices",
  },
  {
    title: "Inhaler pressure drop",
    price: "$35.00 USD",
    originalPrice: "$40.00 USD",
    image: "/uploads/product7.svg",
    category: "Medicines",
  },
  {
    title: "Multi vitamin",
    price: "$20.00 USD",
    originalPrice: "$25.00 USD",
    image: "/uploads/product8.svg",
    category: "Medicines",
  },
  {
    title: "Microscope",
    price: "$45.00 USD",
    originalPrice: "$50.00 USD",
    image: "/uploads/p1.svg",
    chip: "New",
    category: "Lab",
  },
  {
    title: "Pulse oximeter",
    price: "$19.00 USD",
    originalPrice: "$25.00 USD",
    image: "/uploads/p2.svg",
    chip: "Save 10%",
    category: "Devices",
  },
  {
    title: "Vitamin serum",
    price: "$20.00 USD",
    originalPrice: "$30.00 USD",
    image: "/uploads/p3.svg",
    category: "Medicines",
  },
  {
    title: "High protein",
    price: "$50.00 USD",
    originalPrice: "$60.00 USD",
    image: "/uploads/p4.svg",
    chip: "New",
    category: "Medicines",
  },
  {
    title: "Hair tablets",
    price: "$19.00 USD",
    originalPrice: "$25.00 USD",
    image: "/uploads/Hairtablets.svg",
    category: "Medicines",
  },
  {
    title: "Pressure measuring",
    price: "$25.00 USD",
    originalPrice: "$30.00 USD",
    image: "/uploads/Pressure.svg",
    category: "Devices",
  },
  {
    title: "Diving mask",
    price: "$40.00 USD",
    originalPrice: "$45.00 USD",
    image: "/uploads/Divingmask.svg",
    category: "Accessories",
  },
  {
    title: "Temperature gun",
    price: "$20.00 USD",
    originalPrice: "$25.00 USD",
    image: "/uploads/Temperature.svg",
    category: "Devices",
  },
  {
    title: "Nebulizer mask",
    price: "$15.00 USD",
    originalPrice: "$18.00 USD",
    image: "/uploads/Nebulizer.svg",
    category: "Devices",
  },
];

module.exports = products;
